# Generated by Django 5.2 on 2025-05-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0005_branch_created_by_office_created_by'),
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Splitter', 'Splitter'), ('Coupler', 'Coupler'), ('Transceiver', 'Transceiver'), ('Patch Panel', 'Patch Panel'), ('Optical Switch', 'Optical Switch'), ('Media Converter', 'Media Converter'), ('Network Interface Card (NIC)', 'Network Interface Card (NIC)'), ('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall')], max_length=50, verbose_name='Device Type')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Device Description')),
                ('ratio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Splitter/Coupler Ratio')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='Maximum Speed (Mbps or Gbps)')),
                ('color_coding', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiber Color Coding')),
                ('insertion_loss', models.FloatField(blank=True, null=True, verbose_name='Insertion Loss (dB)')),
                ('return_loss', models.FloatField(blank=True, null=True, verbose_name='Return Loss (dB)')),
                ('port_count', models.IntegerField(blank=True, null=True, verbose_name='Number of Ports')),
                ('supported_protocols', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supported Protocols')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office', verbose_name='Office')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opticalfiber_app.staff', verbose_name='Staff Member')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(verbose_name='Port Number')),
                ('port_type', models.CharField(choices=[('SFP', 'SFP'), ('Ethernet', 'Ethernet'), ('QSFP', 'QSFP')], max_length=50, verbose_name='Port Type')),
                ('speed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Port Speed (Gbps)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='networkdevice_app.networkdevice', verbose_name='Device')),
            ],
        ),
    ]
