# Generated by Django 5.2 on 2025-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice_app', '0002_deviceport_created_at_deviceport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='logitutde',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
