# Generated by Django 5.2 on 2025-08-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice_app', '0003_networkdevice_latitude_networkdevice_logitutde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('OLT', 'OLT'), ('ONT', 'ONT'), ('Splitter', 'Splitter'), ('Coupler', 'Coupler'), ('Transceiver', 'Transceiver'), ('Patch Panel', 'Patch Panel'), ('Optical Switch', 'Optical Switch'), ('Media Converter', 'Media Converter'), ('Network Interface Card (NIC)', 'Network Interface Card (NIC)'), ('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall')], max_length=50, verbose_name='Device Type'),
        ),
    ]
