# Generated by Django 5.2 on 2025-12-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice_app', '0004_alter_networkdevice_device_type'),
        ('office', '0005_branch_created_by_office_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_power', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='office.office')),
            ],
        ),
        migrations.CreateModel(
            name='CouplerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupler_ratio', models.CharField(max_length=100)),
                ('tap_km', models.FloatField()),
                ('tap_output_dbm', models.FloatField()),
                ('throughput_km', models.FloatField()),
                ('through_output_dbm', models.FloatField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couplers', to='networkdevice_app.design')),
            ],
        ),
    ]
