# Generated by Django 5.2 on 2025-12-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice_app', '0005_design_couplercalculation'),
        ('opticalfiber_app', '0005_staff_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='opticalfiber_app.company'),
        ),
    ]
