# Generated by Django 5.2 on 2025-05-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0002_alter_office_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.JSONField()),
                ('length_km', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_routes', to='office.office')),
            ],
            options={
                'verbose_name': 'Fiber Route',
                'verbose_name_plural': 'Fiber Routes',
            },
        ),
    ]
