# Generated by Django 5.2 on 2025-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_branch'),
        ('route_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberroute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiberroute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fiberroute',
            name='length_km',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fiberroute',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='fiberroute',
            index=models.Index(fields=['office', 'name'], name='route_app_f_office__464af0_idx'),
        ),
    ]
