# Generated by Django 5.2 on 2025-05-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticalfiber_app', '0003_otp'),
        ('route_app', '0002_fiberroute_is_deleted_fiberroute_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberroute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_routes_created', to='opticalfiber_app.staff'),
        ),
    ]
