# Generated by Django 5.2 on 2025-05-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0003_fiberroute_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiberroute',
            name='slug',
        ),
    ]
