# Generated by Django 5.2 on 2025-05-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0004_remove_fiberroute_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiberroute',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='fiberroute',
            name='route_app_f_office__464af0_idx',
        ),
    ]
