# Generated by Django 5.2 on 2025-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
