# Generated by Django 5.2 on 2025-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='type',
            field=models.CharField(default='branch', max_length=50),
        ),
    ]
