# Generated by Django 5.2 on 2025-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='type',
        ),
    ]
