# Generated by Django 5.2 on 2025-05-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_branch'),
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches_created', to='opticalfiber_app.staff'),
        ),
        migrations.AddField(
            model_name='office',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices_created', to='opticalfiber_app.staff'),
        ),
    ]
