# Generated by Django 5.2 on 2025-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_payment_razorpay_order_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='cashfree_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='cashfree_payment_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
