# Generated by Django 5.2 on 2025-12-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_rename_razorpay_order_id_payment_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cashfree_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cashfree_payment_session_id',
            new_name='payment_session_id',
        ),
    ]
