# Generated by Django 5.2 on 2025-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_rename_cashfree_order_id_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
