# Generated by Django 5.2 on 2025-05-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0004_branch'),
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.JSONField(help_text="Include latitude and longitude as JSON, e.g. {'lat': 11.25, 'lng': 75.79}")),
                ('post_no', models.CharField(blank=True, max_length=255, null=True)),
                ('junction_type', models.CharField(choices=[('main', 'Main Junction'), ('child', 'Child Junction')], db_index=True, default='main', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junctions_created', to='opticalfiber_app.staff')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctions', to='office.office')),
            ],
            options={
                'verbose_name': 'Junction',
                'verbose_name_plural': 'Junctions',
                'permissions': [('can_view_sensitive_junctions', 'Can view sensitive junctions')],
                'indexes': [models.Index(fields=['name', 'location'], name='junction_ap_name_4f5180_idx'), models.Index(fields=['junction_type'], name='junction_ap_junctio_7b5f2e_idx'), models.Index(fields=['office', 'is_active'], name='junction_ap_office__0e2971_idx')],
            },
        ),
    ]
