# Generated by Django 5.2 on 2025-05-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction_app', '0001_initial'),
        ('networkdevice_app', '0002_deviceport_created_at_deviceport_updated_at_and_more'),
        ('office', '0005_branch_created_by_office_created_by'),
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Junction Box Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('junction_type', models.CharField(choices=[('Main', 'Main'), ('Child', 'Child')], default='Child', max_length=50, verbose_name='Junction Box Type')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office', verbose_name='Office')),
                ('parent_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_junction_boxes', to='junction_app.junctionbox', verbose_name='Parent Junction Box')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticalfiber_app.staff', verbose_name='Staff Member')),
            ],
        ),
        migrations.CreateModel(
            name='JunctionBoxDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_boxes', to='networkdevice_app.networkdevice', verbose_name='Network Device')),
                ('junction_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='junction_app.junctionbox', verbose_name='Junction Box')),
            ],
        ),
        migrations.DeleteModel(
            name='Junction',
        ),
    ]
