# Generated by Django 5.2 on 2025-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junction_app', '0002_junctionbox_junctionboxdevice_delete_junction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junctionbox',
            name='parent_box',
        ),
    ]
