# Generated by Django 5.2 on 2025-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction_app', '0003_remove_junctionbox_parent_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionbox',
            name='post_code',
            field=models.CharField(default=1, max_length=10, verbose_name='Post Code'),
            preserve_default=False,
        ),
    ]
