# Generated by Django 5.2 on 2025-05-10 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction_app', '0004_junctionbox_post_code'),
        ('opticalfiber_app', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junctionbox',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opticalfiber_app.staff', verbose_name='Staff Member'),
            preserve_default=False,
        ),
    ]
