# Generated by Django 5.2 on 2025-05-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junction_app', '0005_alter_junctionbox_staff'),
        ('office', '0005_branch_created_by_office_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junctionbox',
            name='location',
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='junctionbox',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='junctionbox',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_boxes', to='office.office', verbose_name='Office'),
        ),
    ]
